### ISSUE TITLE
IndexOutOfRangeException in SampleBrgContainer->Start()

### ISSUE THREAD

**Issue by wearplugins** [LizzyFox-code/BrgContainer#6]
I have exception in SampleBrgContainer.cs. 
Unity3D 2023.2.19f1
BRG Container 1.3.3
URP 16.0.6

IndexOutOfRangeException: Index 0 must be from 0 to 0 (exclude).
BrgContainer.Runtime.BatchInstanceDataBuffer.WriteInstanceData[T] (System.Int32 index, System.Int32 propertyId, T itemData) (at D:/BrgContainer-main/Runtime/BatchInstanceDataBuffer.cs:68)
BrgContainer.Runtime.BatchInstanceDataBufferExtensions.SetTRS (BrgContainer.Runtime.BatchInstanceDataBuffer buffer, System.Int32 index, Unity.Mathematics.float3 position, Unity.Mathematics.quaternion rotation, Unity.Mathematics.float3 scale) (at D:/BrgContainer-main/Runtime/BatchInstanceDataBufferExtensions.cs:50)
Samples.Hello_World.SampleBrgContainer.Start () (at Assets/Scripts/Samples/HelloWorld/SampleBRGContainer.cs:71)

System.IndexOutOfRangeException: Index 0 must be from 0 to 0 (exclude).
This Exception was thrown from a job compiled with Burst, which has limited exception support.
0x00007fff3de730ce (aa476a1d47417c617de4a22e6f9eaa4) burst_Abort_Trampoline
0x00007fff3de7202d (aa476a1d47417c617de4a22e6f9eaa4) BrgContainer.Runtime.BatchInstanceDataBuffer.ReadInstanceData<BrgContainer.Runtime.PackedMatrix> (at D:/BrgContainer-main/Runtime/BatchInstanceDataBuffer.cs:92)
0x00007fff3de72ed2 (aa476a1d47417c617de4a22e6f9eaa4) Unity.Jobs.IJobExtensions.JobStruct`1<Samples.Hello_World.AverageCenterJob>.Execute(ref Samples.Hello_World.AverageCenterJob data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, ref Unity.Jobs.LowLevel.Unsafe.JobRanges ranges, int jobIndex) -> void_762974e6686d5b773f8da150698ed490 from UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null (at D:/TestBRG2/Library/PackageCache/com.unity.burst@1.8.13/.Runtime/unknown/unknown:0)
0x00007fff3de72cbd (aa476a1d47417c617de4a22e6f9eaa4) afeb774f5e7c909df5364a343503b6c9
0x00007ffe82b0bb35 (Unity) ExecuteJob

**Comment by LizzyFox-code** [comment]
![2024-04-23_12-29-34](https://github.com/LizzyFox-code/BrgContainer/assets/26055406/47fbe691-6f98-4705-b626-1c73f2c35bbe)

Done!

**Comment by wearplugins** [comment]
Thanks for your great work! This is Unity3D 2023.2.19f1? Because I still have an empty scene, with moving pivot.

![image](https://github.com/LizzyFox-code/BrgContainer/assets/83076762/f8aec3c8-768f-4e80-9b10-f5773f19c47e)
![image](https://github.com/LizzyFox-code/BrgContainer/assets/83076762/f0ddf753-ef5a-44c6-a1e5-d1c86254e7b1)

Maybe there is a problem with the shader which is not in the package. Or in the project settings.

**Comment by LizzyFox-code** [comment]
Thanks!

Oh, no, I use Unity 2023.1.x version :( 
Try to set a material with another shader or just another prefab. Also, you can check it with the Frame Debugger.

**Comment by wearplugins** [comment]
Thanks!
